-- Delete all data from all tables to force re-seed
TRUNCATE TABLE iam.tenant_memberships CASCADE;
TRUNCATE TABLE iam.role_permissions CASCADE;
TRUNCATE TABLE iam.user_claims CASCADE;
TRUNCATE TABLE iam.user_devices CASCADE;
TRUNCATE TABLE iam.sessions CASCADE;
TRUNCATE TABLE iam.security_events CASCADE;
TRUNCATE TABLE iam.refresh_tokens CASCADE;
TRUNCATE TABLE iam.email_verification_tokens CASCADE;
TRUNCATE TABLE iam.password_reset_tokens CASCADE;
TRUNCATE TABLE iam.two_factor_backup_codes CASCADE;
TRUNCATE TABLE iam.users CASCADE;
TRUNCATE TABLE iam.tenants CASCADE;
TRUNCATE TABLE iam.roles CASCADE;
TRUNCATE TABLE iam.permissions CASCADE;
TRUNCATE TABLE iam.tenant_settings CASCADE;
TRUNCATE TABLE iam.tenant_security_policies CASCADE;
TRUNCATE TABLE iam.policy_rules CASCADE;
TRUNCATE TABLE iam.audit_logs CASCADE;
